docker push rust-builder image
paritytech/scripts pull request #219
Opened 2020-07-29 10:09 UTC by fevo1971

`rust-builder:latest` docker image was never pushed.

2020-08-03 09:39 UTC, gabreal commented
not sure about the permissions though, needs to be verified on the first run.

2020-09-01 18:10 UTC, TriplEight commented
Is this tag needed somewhere? It's a long time gone and last time was mentioned as a temporary measure. I suggest removing the `docker tag` line.

2020-09-02 11:53 UTC, gabreal commented
I'm also fine with removing it entirely, not sure anymore where it was needed. do you @fevo1971 ?

2020-09-04 08:56 UTC, TriplEight requested changes
I've searched the whole github a couple of months ago to make sure that no active projects are using `rust-builder` or `substrate-ci-linux` to transit to `ci-linux` safely and even did PRs in a couple of third-party projects (and obviously in ours as well) to rename the image.
I doubt that something's changed since that time. 
After this change, I can remove the older images from docker hub for good.

2020-09-04 08:56 UTC, TriplEight commented on .gitlab-ci.yml
> +    - docker push parity/rust-builder:latest
```suggestion
```

2021-02-19 09:25 UTC, TriplEight commented
this is a tiny bit outdated

2021-02-19 09:25 UTC, closed without merging