Enable binaryen-sys build in ink! container
paritytech/scripts pull request #235
Opened 2020-11-02 12:06 UTC by cmichi

Escalated from https://github.com/paritytech/cargo-contract/pull/95.

2020-11-02 13:43 UTC, TriplEight requested changes

2020-11-02 13:43 UTC, TriplEight commented on dockerfiles/ink-ci-linux/Dockerfile
>  RUN	set -eux; \
```suggestion
# Necessary for building binaryen-sys, which is part of cargo-contract's
# binaryen dependency
ENV CXX="/usr/bin/clang++-8"

RUN	set -eux; \
```

2020-11-02 13:43 UTC, TriplEight commented on dockerfiles/ink-ci-linux/Dockerfile
> +# Necessary for building binaryen-sys, which is part of cargo-contract's
```suggestion
# Necessary for building binaryen-sys, which is part of cargo-contract's
```

2020-11-02 13:43 UTC, TriplEight commented on dockerfiles/ink-ci-linux/Dockerfile
> +# binaryen dependency
```suggestion
# binaryen dependency
```

2020-11-02 13:43 UTC, TriplEight commented on dockerfiles/ink-ci-linux/Dockerfile
> +  export CXX="/usr/bin/clang++-8" \
```suggestion
  export CXX="/usr/bin/clang++-8" \
```

2020-11-02 13:43 UTC, TriplEight commented on dockerfiles/ink-ci-linux/Dockerfile
>  RUN	set -eux; \
environment variable in Dockerfiles are set via `ENV`

2020-11-02 15:03 UTC, TriplEight commented
That doesn't work with some other dependencies, could there be any other way instead of changing the linker for everything?

2020-11-02 15:09 UTC, cmichi commented
@TriplEight Ok, hmm, the only way I see is putting it back in the `.gitlab-ci.yml` from `cargo-contracts`, so that it affects only what it strictly needs to affect :/.

2020-11-02 15:19 UTC, TriplEight commented
here's everything we have in the CI image:
```
root@cb1df0df5555:/builds# ls /usr/bin/ | grep clang
clang
clang++
clang++-7
clang-7
clang-cpp-7
```

And you've mentioned there should be C++14

2020-11-10 17:45 UTC, TriplEight commented
Done in https://github.com/paritytech/scripts/pull/237

2020-11-10 17:45 UTC, closed without merging