New `parity-keyring` image
paritytech/scripts pull request #426
Opened 2022-05-31 17:04 UTC by chevdor

Introduce a new image + few minor fixes

2022-06-01 09:45 UTC, coderobe requested changes

2022-06-01 09:45 UTC, coderobe commented on dockerfiles/parity-keyring/Dockerfile
> +	io.parity.image.source="https://github.com/paritytech/scripts/blob/${VCS_REF}/dockerfiles/gnupg/Dockerfile" \
```suggestion
	io.parity.image.source="https://github.com/paritytech/scripts/blob/${VCS_REF}/dockerfiles/parity-keyring/Dockerfile" \
```

2022-06-01 09:45 UTC, coderobe commented on dockerfiles/parity-keyring/Dockerfile
> +	io.parity.image.documentation="https://github.com/paritytech/scripts/blob/${VCS_REF}/dockerfiles/gnupg/README.md" \
```suggestion
	io.parity.image.documentation="https://github.com/paritytech/scripts/blob/${VCS_REF}/dockerfiles/parity-keyring/README.md" \
```

2022-06-01 13:25 UTC, coderobe approved these changes

2022-06-01 14:58 UTC, merged

2022-06-02 09:13 UTC, EgorPopelyaev approved these changes